title: Ming Chu
logo: /assets/img/headshot.png
description: Data Analyst | Machine Learning Researcher | Healthcare IT Specialist
theme: jekyll-theme-minimal
#show_downloads: false

sass:
  style: compressed
